### ISSUE TITLE
Support for more than two languages

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#31]
Currently only two languages are supported in WATM, but there is a need to switch between 3 or more languages. 

This change would involve:

- adding a drop down  3 or more languages, could be a text link switcher too (button is only for 2 languages)

- reading the configuration files(s) and script from a WATM-server

- support for a new translation file structure for a separate file for each language

- configuring number of languages and language names in the javascript installation script, as well as  a fallback message in the console if the script doesn't load successfully

**Comment by mDisna** [comment]
> **What would it take to support more than 2 languages in WATM?**
> - The button would need to be a switcher with labels for each language configurable
> - The storage of each translation may need to be modified from the current column layout

I believe the toggle can be taken care of with a radio button or dropdown list, populated from the configuration settings. The `setIsMultilingual` cookie would then store the language code rather than a boolean. 

We can also create a hook to allow the toggle to be applied to custom elements, such as Wild Apricot menu items or links.

The CSV file loaded would depend on the language code stored in `setIsMultilingual`. In order to remove duplication of work when setting up the CSVs, we may need to run the replacement routine twice with two separate files - first a default replacement file, and then the language file.

**Comment by asirota** [comment]
So there would also be a configuration file to identify which languages are supported and where the translations are for each file? 

And we would remove the alternative language field from the current csv and keep that as a css and replacement text config file only?

The separate pass would work I think. I don't think it would take too much longer to parse a second file.

Question: Would it load up all language files each time or only for the current selected language?

**Comment by mDisna** [comment]
> **Would there also be a configuration file to identify which languages are supported and where the translations are for each file?**

I envision this information would be added to the JS on the WA site like this:

```
<script>
/* Array of available languages */
watm_language_name[0] = "English"; // Label
watm_language_className[0] = ".english"; // Class
watm_language_csv_slug[0] = "_en"; // Unique text before the ".csv"

watm_language_name[1] = French"; // Label
watm_language_className[1] = ".french"; // Class
watm_language_csv_slug[1] = "_fr"; // Unique text before the ".csv"

watm_language_name[2] = "Spanish"; // Label
watm_language_className[2] = ".spanish"; // Class
watm_language_csv_slug[2] = "_es"; // Unique text before the ".csv"
</script>
```

The CSV files would then be named as follows:
- `wildapricot-textmanager-config.csv` - default configuration file
- `wildapricot-textmanager-config_en.csv` - english configuration file
- `wildapricot-textmanager-config_fr.csv` - french configuration file
- `wildapricot-textmanager-config_es.csv` - spansih configuration file

> **Would we remove the alternative language field from the current csv and keep that as a css and replacement text config file only?**

No, if there is only one alternative language being used then the client can just use one configuration file.

> **Would it load up all language files each time or only for the current selected language?**

Only the file for the selected language (plus the default one) would load

**Comment by Crednib** [comment]
what would happen if they wanted to change from french to spanish and then back to english? (this is especially the case when I'm working on verifying that the translations are working in admin).
  
  
   
  
  
   Thank you!
   Carol
  
  
   
    On 05/17/2022 6:47 AM mDisna ***@***.***> wrote:
   
   
    
   
   
    
   
   
   
    Would there also be a configuration file to identify which languages are supported and where the translations are for each file?
   
   I envision this information would be added to the JS on the WA site like this:
   <script>
/* Array of available languages */
watm_language_name[0] = "English"; // Label
watm_language_className[0] = ".english"; // Class
watm_language_csv_slug[0] = "_en"; // Unique text before the ".csv"

watm_language_name[1] = French"; // Label
watm_language_className[1] = ".french"; // Class
watm_language_csv_slug[1] = "_fr"; // Unique text before the ".csv"

watm_language_name[2] = "Spanish"; // Label
watm_language_className[2] = ".spanish"; // Class
watm_language_csv_slug[2] = "_es"; // Unique text before the ".csv"
</script>

   The CSV files would then be named as follows:
   
    wildapricot-textmanager-config.csv - default configuration file
    wildapricot-textmanager-config_en.csv - english configuration file
    wildapricot-textmanager-config_fr.csv - french configuration file
    wildapricot-textmanager-config_es.csv - spansih configuration file
   
   
    Would we remove the alternative language field from the current csv and keep that as a css and replacement text config file only?
   
   No, if there is only one alternative language being used then the client can just use one configuration file.
   
    Would it load up all language files each time or only for the current selected language?
   
   Only the file for the selected language (plus the default one) would load
   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
  
  
   
  
  
   
    Best Regards,
   
   
    Carol Binder, NewPath Consulting, CRM/Database Migration

**Comment by mDisna** [comment]
This will not be a problem. There will be a dropdown menu from where they can select whichever language they want and freely switch between them. Selecting a language will refresh the page and load the translation file for that language.
