### ISSUE TITLE
Editor UI feedback for 2.0

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#78]
I recorded a bit of feedback on the UI for improvement

https://vimeo.com/730417762/8abfa6db6c

**Comment by asirota** [comment]
Here's the error in Console I am getting when trying save to site/download file

Uncaught SyntaxError: Unexpected token c in JSON at position 211
    at JSON.parse (<anonymous>)
    at generateCSV (scripts.js:229:15)
    at HTMLButtonElement.<anonymous> (scripts.js:107:19)
editor.html:1
       Uncaught SyntaxError: Unexpected token c in JSON at position 211
    at JSON.parse (<anonymous>)
    at generateCSV (scripts.js:229:15)
    at HTMLButtonElement.<anonymous> (scripts.js:107:19)
editor.html:1
       Uncaught SyntaxError: Unexpected token c in JSON at position 211
    at JSON.parse (<anonymous>)
    at generateCSV (scripts.js:229:15)
    at HTMLButtonElement.<anonymous> (scripts.js:107:19)
editor.html:1
       Uncaught SyntaxError: Unexpected token c in JSON at position 211
    at JSON.parse (<anonymous>)
    at generateCSV (scripts.js:229:15)
    at downloadCSV (scripts.js:188:17)
    at HTMLButtonElement.<anonymous> (scripts.js:145:5)
editor.html:1
       Uncaught SyntaxError: Unexpected token c in JSON at position 211
    at JSON.parse (<anonymous>)
    at generateCSV (scripts.js:229:15)
    at HTMLButtonElement.<anonymous> (scripts.js:107:19)
DevTools failed to load source map: Could not load content for https://newpathconsulting.wildapricot.org/resources/Theme/WildApricotTextManager/watm-editor/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by mDisna** [comment]
The issue is that this is using iframes - notice the two scrollbars.

The buttons can not be moved next to the other buttons - everything under the "Exit Inspector" button in the editor is in an iframe.

Within the iframe, the buttons are static, but in trying to calculate the correct height to display based on screen size, a scrollbar is being shown.

On longer files, you'll notice a second scrollbar as well. The contents of the table scrolls while the header remains static, but the outer container also has a scrollbar, which then hides the header.

The same issue occurs with the full screen editor, and it's basically because we can't set an iframe to match the height of it's contents.

I will look into how we can improve this, but our options are limited.

**Comment by asirota** [comment]
Why can't the buttons be in a separate iframe to the right of the buttons? Or will that make it overly complex?

**Comment by asirota** [comment]
I note that in the new window editor, you need to tab to get over to styles. It would be good to have a horizontal scroll bar.

**Comment by mDisna** [comment]
iframes can't interact with each other - i am investigating other options

You shouldn't need to scroll - please post a screenshot and list your monitor size

**Comment by asirota** [comment]
When editing french.csv

when editing in an a main editor window, have to scroll across to see style, no horizontal scroller though

![image](https://user-images.githubusercontent.com/458134/180494750-0e48a574-4979-4837-83a3-09815314e749.png)

**Comment by asirota** [comment]
Great use of a new editor control. Way better!
