### ISSUE TITLE
add login and timestamp to Notes field on save of config file

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/watm#95]
To keep track of which lines were added/edited/updated, let's use the Notes field and add

WebDAV login email : <timestamp> to show that someone edited/added a line. This can be added during a save automatically or when you just navigate the file. Save would be more ideal though.

**Comment by mDisna** [comment]
We do not have access to the email address, but it's would better not to have it anyway since it'll be a security issue

I can add the timestamp, but here are some issues to consider -
- Keeping track of and comparing all the cells to see if they've been updated could make saving take much longer
- Using the notes field would either overwrite anything already there, or perpetually append it on each save
- A new column could be used, but there is already limited space - could we remove the WA reference column since the notes could be used for that instead?

**Comment by asirota** [comment]
I like the wa reference column for keeping items together in groups. In particular it's useful when editing in excel. 

I'm ok with overwriting what was in the notes field on every update.

**Comment by asirota** [comment]
What's the new functionality in the beta here?

**Comment by mDisna** [comment]
When you update any column besides the Notes column, the Notes column for that row will be updated with the current date

**Comment by asirota** [comment]
if I edit the notes field with new data, another change erases with the new functionality, probably best to introduce a hidden column you can show/hide with this information since notes can easily be overwritten.
